### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by diegosz**
Fix connections for an account changed subject to $SYS.ACCOUNT.<id>.SERVER.CONNS

### CODE REVIEW

**Comment by matthiashanel** [comment]
@diegosz that is the right subject to mention. out of curiosity, did you have issues with the old one, which should still work?

**Comment by matthiashanel** [comment]
I just tried it out, with account named USERS. Both messages get sent.

```
[#12] Received on "$SYS.SERVER.ACCOUNT.USERS.CONNS"
{"type":"io.nats.server.advisory.v1.account_connections","id":"u3ZypzZOyeBSNbOGfty9TF","timestamp":"2022-04-07T17:23:01.977889Z","server":{"name":"a","host":"0.0.0.0","id":"NBF425ZSZHQC6QCJEOPMEV3HD3QGOC5IAEXQXMWYBS3GXZEGGQISRQ2G","ver":"2.8.0-beta.11","seq":32,"jetstream":false,"time":"2022-04-07T17:23:01.977907Z"},"acc":"USERS","conns":2,"leafnodes":0,"total_conns":2}

[#13] Received on "$SYS.ACCOUNT.USERS.SERVER.CONNS"
{"type":"io.nats.server.advisory.v1.account_connections","id":"u3ZypzZOyeBSNbOGfty9TF","timestamp":"2022-04-07T17:23:01.977889Z","server":{"name":"a","host":"0.0.0.0","id":"NBF425ZSZHQC6QCJEOPMEV3HD3QGOC5IAEXQXMWYBS3GXZEGGQISRQ2G","ver":"2.8.0-beta.11","seq":33,"jetstream":false,"time":"2022-04-07T17:23:01.977921Z"},"acc":"USERS","conns":2,"leafnodes":0,"total_conns":2}
```

**Review by matthiashanel — APPROVED** [review]
LGTM. definitely the better subject to reference

**Comment by diegosz** [comment]
awesome, many thanks!

**Pull request merged**
