### PR TITLE
Update JetStream+Docker, add Docker NGS Leaf Nodes

### PR DESCRIPTION
**Pull request by mprimi**

### CODE REVIEW

**Review by gcolliso — APPROVED** [review]
lgtm - thanks @mprimi

**Comment by gcolliso** [comment]
@mprimi this is in draft mode - are we ready to push to prod?

**Comment by mprimi** [comment]
@gcolliso rebased and squashed, ready for merge.
(one question: the new file does not appear in any of the indices / table of content -- is that automatic or are there steps i should run?)

**Comment by gcolliso** [comment]
@mprimi you will need to add the new file to the summary.md file as that is how the outline/TOC is built

**Comment by mprimi** [comment]
Thank you @gcolliso, updated summary.

**Pull request merged**
