### PR TITLE
reference ArtifactHub for Helm configuration

### PR DESCRIPTION
**Pull request by caleblloyd**
Helm chart documentation is automatically uploaded to ArtifactHub every time a release is cut.  Link to ArtifactHub instead of presenting potentially stale information on the NATS docs website.

### CODE REVIEW

**Comment by caleblloyd** [comment]
It may make more sense to eliminate this page altogether and put the link to ArtifactHub at the bottom of this page:

https://docs.nats.io/running-a-nats-service/nats-kubernetes

**Comment by gcolliso** [comment]
IMO I think we should keep the page that allows it to be on the left menu and possibly easier to find if you are just looking through.

**Review by wallyqs — APPROVED** [review]
sounds good to me to point to artifacthub instead

**Comment by caleblloyd** [comment]
Linking off-site is not great for the GitBook format...  I will reflect the most up-to-date Helm configuration here but also preserve the link to ArtifactHub

**Comment by caleblloyd** [comment]
Updated; please re-review

**Comment by gcolliso** [comment]
lgtm

**Pull request merged**
