### PR TITLE
Document $JS.ACK v2 format

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Comment by bruth** [comment]
@jnmoyne I just realized (thanks to @wallyqs) that this does not appear to be implemented in the server yet.

**Comment by bruth** [comment]
Referring to this ADR issue which all the clients implement: https://github.com/nats-io/nats-architecture-and-design/issues/49

**Comment by gcolliso** [comment]
@bruth are we still waiting on this one?

**Comment by bruth** [comment]
It is still on hold, converted to draft.

**Comment by bruth** [comment]
Closing for now, will revisit once this format is implemented.

**Pull request closed without merging**
