### PR TITLE
Add JSConsumerDeliveryNakAdvisory documentation

### PR DESCRIPTION
**Pull request by Coffeeri**
This is a follow up to:

+ Issue: https://github.com/nats-io/nats-server/issues/3072
+ Implementation PR: https://github.com/nats-io/nats-server/issues/3074
+ Schema PR: https://github.com/nats-io/jsm.go/pull/375

### CODE REVIEW

**Comment by gcolliso** [comment]
@jnm could you please review when you get the opportunity? Thank you!

**Comment by jnm** [comment]
@gcolliso wrong person

**Comment by jnmoyne** [comment]
LGTM! Thanks for the contribution :)

**Review by jnmoyne — APPROVED** [review]
LGTM

**Comment by Coffeeri** [comment]
@jnmoyne @gcolliso I think this can be merged since this is approved and all mentioned PRs are merged and released.

**Pull request merged**
