### PR TITLE
Add Subject Mapping / Traffic Shaping Documentation

### LINKED ISSUE #252: Add Subject Mapping Documentation
Add documentation around subject mapping.

See the [TestGlobalAccountRouteMappingsConfiguration](https://github.com/nats-io/nats-server/blob/a67704e245a07cef9afc2be551761d28bd8a95e3/server/accounts_test.go#L2783) test for reference.

### PR DESCRIPTION
**Pull request by ColinSullivan1**
Resolves #252 

Signed-off-by: Colin Sullivan <colin@synadia.com>

### CODE REVIEW

**Review by derekcollison — COMMENTED** [review]
I believe we have account level support in JWTs. Should confirm and if so add in that as well.

**Comment by ColinSullivan1** [comment]
Will do.  I left it out (for now) because I didn't see nsc support, but will follow up for sure.

**Comment by ColinSullivan1** [comment]
I added a note that is is supported in JWTs and through the API and that nsc support will be coming soon.

**Comment by gcolliso** [comment]
lgtm - thanks @ColinSullivan1

**Pull request merged**
