### PR TITLE
Streaming: added new auth configuration

### PR DESCRIPTION
**Pull request by kozlovic**
Document the new configuration fields: username, password, token and nkey_seed_file.
Relates to:
https://github.com/nats-io/nats-streaming-server/pull/1100
https://github.com/nats-io/nats-streaming-server/pull/1101

and will be available in the new Streaming release (v0.19.0)

### CODE REVIEW

**Review by gcolliso — COMMENTED** [review]
lgtm - @kozlovic is this ready to be merged?

**Comment by kozlovic** [comment]
We could wait for next NATS Streaming Server release. Do you want me to move that to Draft?

**Comment by gcolliso** [comment]
Nah, I'll just keep an eye out for the release. Thanks!

**Comment by kozlovic** [comment]
@gcolliso Could can merge this one once https://github.com/nats-io/nats-site/pull/592 is merged.

**Comment by gcolliso** [comment]
lgtm

**Pull request merged**
