### PR TITLE
Update and prune k8s docs

### PR DESCRIPTION
**Pull request by bruth**

### CODE REVIEW

**Comment by bruth** [comment]
Need to update the `SUMMARY.md` to remove old links..

**Review by caleblloyd — APPROVED** [review]
LGTM

**Comment by gcolliso** [comment]
Considering so many pages are being deleted, should we either check for links from other sections or put some redirects in for the deleted pages?

**Comment by bruth** [comment]
Yes, good call. I will check.

**Comment by bruth** [comment]
Added the redirects

**Review by gcolliso — APPROVED** [review]
lgtm -thanks @bruth

**Pull request merged**
