### PR TITLE
Add docs on configuration of OCSP

### PR DESCRIPTION
**Pull request by wallyqs**

### CODE REVIEW

**Comment by gcolliso** [comment]
@wallyqs when is NATS 2.3 supposed to be released?

**Comment by wallyqs** [comment]
Not sure, we can leave open until it is released.

**Comment by gcolliso** [comment]
Just moved this to Draft status until NATS v2.3 is released.

**Comment by wallyqs** [comment]
NATS 2.3 is released so let's merge 🙌

**Pull request merged**
