### PR TITLE
adding doc for verify_cert_and_check_known_urls

### PR DESCRIPTION
**Pull request by matthiashanel**
This is a new feature similar to verify_and_map, but without the extra config.
I'll be using this in other documents, maybe commit prior to being released?

### CODE REVIEW

**Review by kozlovic — APPROVED** [review]
LGTM

**Comment by gcolliso** [comment]
@matthiashanel are we ok to merge this now?

**Comment by matthiashanel** [comment]
Hey Ginger, maybe hod off with the merge till next week.

**Comment by gcolliso** [comment]
Ok - will do. Thanks!

**Comment by matthiashanel** [comment]
> Ok - will do. Thanks!

Hey @gcolliso merging would actually be good

**Comment by gcolliso** [comment]
lgtm - thanks @matthiashanel

**Pull request merged**
