### PR TITLE
Add section for minimum requirements

### PR DESCRIPTION
**Pull request by bruth**
This (hopefully) simplifies #321 to focus on the bare minimum requirement no matter the compute environment. The recommended/upper bound is variable, so stating a _preferred_ size doesn't seem all that useful.

After a very basic test, I sort of arbitrarily choose 64MB for a JS-enabled server

### CODE REVIEW

**Comment by gcolliso** [comment]
@bruth are you waiting for another review before we publish?

**Comment by bruth** [comment]
We can keep it open. @caleblloyd is running some benchmarks to get some more baseline that we can summarize and add to this PR.

**Comment by caleblloyd** [comment]
These seem like sane defaults, I ran a few tests on a machine with a fast CPU and fast Storage.  Failures were either due to OOM or the Msg/Second target was not reached.  I did use GOMEMLIMIT=90% of the hard memory limit.

**Cluster Size 1, 1 CPU per Server, 128B message size, 1 subscriber, no JetStream**

```
Status              Memory      Publishers   Msg/Publisher      Msg/Second 
PASSED                32Mi               1               1               1 
PASSED                32Mi               1              10              10 
PASSED                32Mi               1             100             100 
PASSED                32Mi               1            1000            1000 
PASSED                32Mi              10               1              10 
PASSED                32Mi              10              10             100 
PASSED                32Mi              10             100            1000 
FAILED - slow         32Mi              10            1000           10000 
PASSED                32Mi             100               1             100 
PASSED                32Mi             100              10            1000 
PASSED                32Mi             100             100           10000 
PASSED                32Mi             100            1000          100000 
FAILED - OOM          32Mi            1000               1            1000 
FAILED - slow         64Mi              10            1000           10000 
PASSED                64Mi            1000               1            1000 
PASSED                64Mi            1000              10           10000 
PASSED                64Mi            1000             100          100000 
FAILED - OOM          64Mi            1000            1000         1000000 
FAILED - slow        128Mi              10            1000           10000 
FAILED - OOM         128Mi            1000            1000         1000000 
FAILED - slow        256Mi              10            1000           10000 
FAILED - OOM         256Mi            1000            1000         1000000 
```

**Cluster Size 3, 1 CPU per Server, 128B message size, 1 subscriber, no JetStream**

```
Status              Memory      Publishers   Msg/Publisher      Msg/Second 
PASSED                32Mi               1               1               1 
PASSED                32Mi               1              10              10 
PASSED                32Mi               1             100             100 
PASSED                32Mi               1            1000            1000 
PASSED                32Mi              10               1              10 
PASSED                32Mi              10              10             100 
PASSED                32Mi              10             100            1000 
FAILED - slow         32Mi              10            1000           10000 
PASSED                32Mi             100               1             100 
PASSED                32Mi             100              10            1000 
PASSED                32Mi             100             100           10000 
FAILED - slow         32Mi             100            1000          100000 
PASSED                32Mi            1000               1            1000 
PASSED                32Mi            1000              10           10000 
PASSED                32Mi            1000             100          100000 
FAILED - OOM          32Mi            1000            1000         1000000 
FAILED - slow         64Mi              10            1000           10000 
FAILED - slow         64Mi             100            1000          100000 
FAILED - slow         64Mi            1000            1000         1000000 
FAILED - slow        128Mi              10            1000           10000 
FAILED - slow        128Mi             100            1000          100000 
FAILED - slow        128Mi            1000            1000         1000000 
FAILED - slow        256Mi              10            1000           10000 
FAILED - slow        256Mi             100            1000          100000 
FAILED - slow        256Mi            1000            1000         1000000
```

**Cluster Size 1, 1 CPU per Server, 128B message size, JetStream with 1 Replica on File Storage, 1 Pull Subscriber**

```
Status              Memory      Publishers   Msg/Publisher      Msg/Second 
PASSED                32Mi               1               1               1 
PASSED                32Mi               1              10              10 
PASSED                32Mi               1             100             100 
PASSED                32Mi               1            1000            1000 
PASSED                32Mi              10               1              10 
PASSED                32Mi              10              10             100 
PASSED                32Mi              10             100            1000 
FAILED - slow         32Mi              10            1000           10000 
PASSED                32Mi             100               1             100 
PASSED                32Mi             100              10            1000 
FAILED - OOM          32Mi             100             100           10000 
FAILED - OOM          32Mi            1000               1            1000 
FAILED - slow         64Mi              10            1000           10000 
PASSED                64Mi             100             100           10000 
FAILED - OOM          64Mi             100            1000          100000 
PASSED                64Mi            1000               1            1000 
PASSED                64Mi            1000              10           10000 
FAILED - OOM          64Mi            1000             100          100000 
FAILED - slow        128Mi              10            1000           10000 
FAILED - slow        128Mi             100            1000          100000 
FAILED - OOM         128Mi            1000             100          100000 
FAILED - slow        256Mi              10            1000           10000 
PASSED               256Mi             100            1000          100000 
PASSED               256Mi            1000             100          100000 
FAILED - OOM         256Mi            1000            1000         1000000
```

**Cluster Size 3, 1 CPU per Server, 128B message size, JetStream with 3 Replicas on File Storage, 1 Pull Subscriber**

```
Status              Memory      Publishers   Msg/Publisher      Msg/Second 
PASSED                32Mi               1               1               1 
PASSED                32Mi               1              10              10 
PASSED                32Mi               1             100             100 
PASSED                32Mi               1            1000            1000 
PASSED                32Mi              10               1              10 
PASSED                32Mi              10              10             100 
PASSED                32Mi              10             100            1000 
FAILED - slow         32Mi              10            1000           10000 
PASSED                32Mi             100               1             100 
PASSED                32Mi             100              10            1000 
FAILED - OOM          32Mi             100             100           10000 
FAILED - OOM          32Mi            1000               1            1000 
FAILED - slow         64Mi              10            1000           10000 
PASSED                64Mi             100             100           10000 
FAILED - OOM          64Mi             100            1000          100000 
PASSED                64Mi            1000               1            1000 
PASSED                64Mi            1000              10           10000 
FAILED - OOM          64Mi            1000             100          100000 
FAILED - slow        128Mi              10            1000           10000 
FAILED - slow        128Mi             100            1000          100000 
FAILED - OOM         128Mi            1000             100          100000 
FAILED - slow        256Mi              10            1000           10000 
PASSED               256Mi             100            1000          100000 
PASSED               256Mi            1000             100          100000 
FAILED - OOM         256Mi            1000            1000         1000000 
```

Script used: https://gist.github.com/caleblloyd/22683b0b8b0f4bfcacc7174462cf9743

**Review by caleblloyd — APPROVED** [review]

**Comment by gcolliso** [comment]
lgtm

**Pull request merged**
