### PR TITLE
Fixed incorrect backoff docs

### PR DESCRIPTION
**Pull request by roeschter**
See https://github.com/nats-io/nats-server/issues/5856

### CODE REVIEW

**Comment by roeschter** [comment]
Aricart already made PR on this. Pick the better description.

**Comment by gcolliso** [comment]
@roeschter I am confused about this PR. Should it get merged or not?

**Comment by roeschter** [comment]
I'm a bit confused as well. Maybe I merged something into the wrong direction when trying to resolve a conflict. Will delete this and do it again.

**Comment by roeschter** [comment]
Redoing this PR

**Pull request closed without merging**
