### PR TITLE
Add Azure FT mode for STAN to docs

### PR DESCRIPTION
**Pull request by wallyqs**

### CODE REVIEW

**Review by kozlovic — APPROVED** [review]
LGTM

**Review by gcolliso — COMMENTED** [review]
@wallyqs Just checking, you have amended the title of the doc to NATS Streaming Cluster with FT Mode on AWS, but the content is ...Mode on Azure. Is this for AWS or Azure?

**Comment by wallyqs** [comment]
I made the updates so that the both the FT modes for Azure and AWS are on the same page, before used to be only AWS related docs.

**Review by gcolliso — COMMENTED** [review]
lgtm

**Pull request merged**
