### PR TITLE
Editing: English, typos, mostly small fixes

### PR DESCRIPTION
**Pull request by philpennock**
I did not get to the end, more fixes may follow.

Links to current documentation should not use permalinks which will trap users
on older copies of the documentation; I've kept the permalinks for source code
with line number references.

At least one instance of broken markdown has been fixed.  Some typos.  Some
English fixes.

### CODE REVIEW

**Comment by gcolliso** [comment]
Links to other locations/files in docs outside of the doc you're in, need to be in the following format (../../main slug/submain slug/etc.) so Gitbook can translate once merged, for example... 
->https://github.com/nats-io/nats.docs/tree/master/nats-server/configuration/securing_nats/accounts/README.md 
should be (../../nats-server/configuration/securing_nats/accounts/readme.md)

I thought I had fixed them the first time. I will go in and fix them in this PR.

**Comment by gcolliso** [comment]
@matthiashanel if you could review when you get the chance as some things aren't just syntax changes I want to be sure they are conveying the proper idea.

**Review by matthiashanel — APPROVED** [review]
LGTM

**Comment by matthiashanel** [comment]
@philpennock @gcolliso thanks for the changes

**Pull request merged**
