### PR TITLE
Add a mention of the missing $JS.FC.> subject names in the JS API reference

### PR DESCRIPTION
**Pull request by jnmoyne**

### CODE REVIEW

**Comment by gcolliso** [comment]
@jnmoyne I don't see any additional text added to the file. Am I missing something?

**Comment by jnmoyne** [comment]
Very strange, somehow my edits had disappeared. So I re-did them (see new commit)

**Comment by gcolliso** [comment]
Ah... now I can see them :)

**Review by gcolliso — APPROVED** [review]
lgtm

**Pull request merged**
