### PR TITLE
Update shard config option description.

### PR DESCRIPTION
**Pull request by dontlaugh**
shard -> shared

### CODE REVIEW

**Comment by dontlaugh** [comment]
Hey folks, I actually don't know if this config param is right, but it _looks_ like it should be "shared". Is that the case?

(I haven't deployed a jwt server yet, so I don't have an opportunity to find out for myself)

**Comment by matthiashanel** [comment]
Hello @dontlaugh , it is shard from sharding. This option is to avoid having too many files in one directory by means of sharding them. That is putting them in subdirectories named after the last digits(s) in the account name. Does this make sense?

**Review by matthiashanel — CHANGES_REQUESTED** [review]
it is shard from sharding and does not relate to shared.

**Comment by dontlaugh** [comment]
Ah, I see now. Thanks :) So perhaps something like "if true, JWTs will be stored in multiple directories" or "JWTs will be automatically stored in multiple directories"?

**Comment by matthiashanel** [comment]
Yeah I like that. This will also fix the faulty description. I would maybe include smth like this: stored in sub directories of the store directory.

**Comment by dontlaugh** [comment]
@matthiashanel take another look?

**Review by matthiashanel — APPROVED** [review]
LGTM

**Comment by matthiashanel** [comment]
@dontlaugh just did LGTM. Thanks for your contribution!!!

**Comment by gcolliso** [comment]
lgtm - thanks!

**Pull request merged**
