### PR TITLE
Update SUMMARY.md

### PR DESCRIPTION
**Pull request by wallyqs**
Might be needed to have this as a URL published on the docs site: https://github.com/nats-io/nats.docs/blob/master/nats-on-kubernetes/super-cluster-on-digital-ocean.md

### CODE REVIEW

**Comment by wallyqs** [comment]
hmm link somehow not accessible... https://docs.nats.io/nats-on-kubernetes/nats-kubernetes/super-cluster-on-digital-ocean.md

**Comment by gcolliso** [comment]
> hmm link somehow not accessible... https://docs.nats.io/nats-on-kubernetes/nats-kubernetes/super-cluster-on-digital-ocean

It works for me in Github. I'll merge and fix if necessary.

**Comment by wallyqs** [comment]
Thanks @gcolliso it seems that the `super-cluster-on-digital-ocean.md` is not published on the docs site (getting a 404) https://docs.nats.io/nats-on-kubernetes/nats-kubernetes/super-cluster-on-digital-ocean

**Comment by gcolliso** [comment]
Yeah, it was never published to prod so that external link wouldn't work. You can test the links within GitHub to see if they work though.

**Comment by wallyqs** [comment]
ah ok I thought that changes to the docs site were automatically published to docs.nats.io

**Pull request merged**
